{% set name = "reposurgeon" %}
{% set version = "5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/esr/{{ name }}/-/archive/{{ version }}/reposurgeon-{{ version }}.tar.gz
  sha256: a13e758e6bba5f4d17cdfa0ad8956bb864f336ba248b175353f741c3e5d3b089

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - asciidoctor
    - go-licenses
    - git
    - make

test:
  commands:
    - {{ name }} --help

about:
  home: http://www.catb.org/esr/reposurgeon
  license: BSD-2-Clause
  license_file:
    - COPYING
    - license-files_repocutter/
    - license-files_repomapper/
    - license-files_reposurgeon/
    - license-files_repotool/
  summary: Edit version-control repository history
  dev_url: https://gitlab.com/esr/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
