{% set name = "reposurgeon" %}
{% set version = "5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/esr/{{ name }}/-/archive/{{ version }}/reposurgeon-{{ version }}.tar.gz
  sha256: 25c6386739be5bd304cded51d7a92440d8d1cbcbfa9d3c147d1c9b9a373e904e

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - asciidoctor
    - go-licenses
    - git
    - make

test:
  commands:
    - {{ name }} --help

about:
  home: http://www.catb.org/esr/reposurgeon
  license: BSD-2-Clause
  license_file:
    - COPYING
    - license-files_repocutter/
    - license-files_repomapper/
    - license-files_reposurgeon/
    - license-files_repotool/
  summary: Edit version-control repository history
  dev_url: https://gitlab.com/esr/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
