schema_version: 1

context:
  version: "5.4"

package:
  name: reposurgeon
  version: ${{ version }}

source:
  url: https://gitlab.com/esr/reposurgeon/-/archive/${{ version }}/reposurgeon-${{ version }}.tar.gz
  sha256: 52cc10255b10a160ee07f94d6981b924cf000642a4e2c9c47ff33520b3a7f9b6

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - asciidoctor
    - go-licenses
    - git
    - make

tests:
  - script:
      - reposurgeon --help

about:
  license: BSD-2-Clause
  license_file:
    - COPYING
    - license-files_repocutter/
    - license-files_repomapper/
    - license-files_reposurgeon/
    - license-files_repotool/
  summary: Edit version-control repository history
  homepage: http://www.catb.org/esr/reposurgeon
  repository: https://gitlab.com/esr/reposurgeon

extra:
  recipe-maintainers:
    - danielnachun
