schema_version: 1

context:
  version: "5.7"

package:
  name: reposurgeon
  version: ${{ version }}

source:
  url: https://gitlab.com/esr/reposurgeon/-/archive/${{ version }}/reposurgeon-${{ version }}.tar.gz
  sha256: e0875064f166348b37d190ba8c28f394949f0cfb4b397da97891d87c15e24ec4

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - asciidoctor
    - go-licenses
    - git
    - make

tests:
  - script:
      - reposurgeon --help

about:
  license: BSD-2-Clause
  license_file:
    - COPYING
    - license-files_repocutter/
    - license-files_repomapper/
    - license-files_reposurgeon/
    - license-files_repotool/
  summary: Edit version-control repository history
  homepage: http://www.catb.org/esr/reposurgeon
  repository: https://gitlab.com/esr/reposurgeon

extra:
  recipe-maintainers:
    - danielnachun
