schema_version: 1

context:
  version: "5.11"

package:
  name: reposurgeon
  version: ${{ version }}

source:
  url: https://gitlab.com/esr/reposurgeon/-/archive/${{ version }}/reposurgeon-${{ version }}.tar.gz
  sha256: c51bfb9e9e2af6537224b1973872761031250ceadbebf1e292534870e54bdbc0

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - asciidoctor
    - go-licenses
    - git
    - make

tests:
  - script:
      - reposurgeon --help

about:
  license: BSD-2-Clause
  license_file:
    - COPYING
    - license-files_repocutter/
    - license-files_repomapper/
    - license-files_reposurgeon/
    - license-files_repotool/
  summary: Edit version-control repository history
  homepage: http://www.catb.org/esr/reposurgeon
  repository: https://gitlab.com/esr/reposurgeon

extra:
  recipe-maintainers:
    - danielnachun
